spdk:enum: add opt for subnqn
OpenMPDK/xNVMe pull request #110
Opened 2022-06-09 12:01 UTC by karlowich

Make it possible to specify subnqn when running `xnvme enum` using NVMe over Fabrics.

Before this can be merged a test case for this must be added:
- [ ] add test case for subnqn

Signed-off-by: Karl Bonde Torp <k.torp@samsung.com>

2022-06-15 11:16 UTC, karlowich commented on lib/xnvme_be_spdk_dev.c
> +				 "trtype:%s adrfam:%s traddr:%s trsvcid:%d subnqn:'%s'",
Thank you for your feedback!
I have removed the ticks.

As for line 696: You're right I don't know how I missed that. 
Unless that line is changed this PR is useless...
I wonder why we always set the subnqn to 'nqn.2014-08.org.nvmexpress.discovery' 
@safl What do you think?

2022-07-13 11:00 UTC, karlowich commented
@safl The failing test is fixed by #126, it is due to the `cref`/`deref` stuff

2022-08-31 13:49 UTC, karlowich commented
[05a547f](https://github.com/OpenMPDK/xNVMe/pull/110/commits/05a547f661794618808c1e22bec1949af9321d9a) Introduces a qemu setup with two controllers. This causes `xnvme_tests_enum open --count 4 --be spdk` to fail.
I have applied [2b5d955](https://github.com/OpenMPDK/xNVMe/pull/110/commits/2b5d95574ac56c888fb1a13a3b12ab04f5c921d0) to fix this. Thanks @LiadOz

2022-09-01 09:13 UTC, safl requested changes
LGTM, minor stuff:

* ``be:spdk: add opt for subnqn`` to ``api,xnvmec,be:spdk: add subnqn``
* ``ci: test fabrics with subnqn`` to ``ci,toolbox:cijoe: test fabrics with subnqn``
And a couple of inline comments.
Thanks!

2022-09-01 09:13 UTC, safl commented on lib/xnvmec.c
> +	{.opt = XNVMEC_OPT_SUBNQN,
Seems like the clang-formater did not catch this. Perhaps add a newline?

2022-09-01 10:48 UTC, safl approved these changes

2022-09-01 12:11 UTC, merged