Towards NVMe 2.0 compliance
OpenMPDK/xNVMe pull request #143
Opened 2022-08-25 07:59 UTC by ankit-sam

This is the first patch series towards NVMe 2.0 compliance. Changes done so far

- Identify controller data structure
- Identify Namespace data structure
- Update command format for get log page

2022-09-13 15:35 UTC, safl requested changes
Excellent, thank you @ankit-sam 
A couple of minor things inline.

2022-09-14 16:30 UTC, ankit-sam commented on lib/xnvme_spec.c
> +	wrtn += fprintf(stream, "    format MSB: %d\n", idfy->flbas.format_msb);
done

2022-09-14 16:30 UTC, ankit-sam commented on lib/xnvme_spec.c
> +	wrtn += fprintf(stream, "    format LSB: %d\n", idfy->flbas.format);
done, thanks

2022-09-14 19:11 UTC, safl approved these changes

2022-09-14 21:54 UTC, merged