be:spdk: change default nsid to 1
OpenMPDK/xNVMe pull request #152
Opened 2022-09-13 10:47 UTC by karlowich

Currently, spdk fails if nsid is not provided.
`--dev-nsid` is optional for `xnvme info`, however if unset it will fail with the userspace driver.
This results in a poor user experience, since the error message is "Input/output error"

closes #131 
(This solution seemed more elegant than making `--dev-nsid` a mandatory argument to `xnvme info`)

2022-09-13 14:15 UTC, safl commented
The ``libvfn`` backend could benefit for this as well. So, how about adding this to ``xnvme_opts_default()`` instead?

2022-09-13 14:31 UTC, karlowich commented
The reason I wanted to keep it "local" to spdk was because of [this](https://github.com/OpenMPDK/xNVMe/blob/66a0458c5481e1180ad9938647500bd837988545/lib/xnvme_be_macos_admin.c#L63)

It seems that maybe nsid has a different meaning depending on the backend.
However, `nsid == 1` seems like a sensible default

2022-09-13 14:44 UTC, safl commented
> The reason I wanted to keep it "local" to spdk was because of [this](https://github.com/OpenMPDK/xNVMe/blob/66a0458c5481e1180ad9938647500bd837988545/lib/xnvme_be_macos_admin.c#L63)
> 
> It seems that maybe nsid has a different meaning depending on the backend. However, `nsid == 1` seems like a sensible default

That is just a macos-specific handling of the interface provided to do what it wants to do. ``nsid`` should in the public API mean what is defined in the spec. so that is fine.

2022-09-15 10:56 UTC, karlowich commented
@safl This does not work as of right now due to the issue described here: #154

2022-09-16 13:36 UTC, safl commented
This is looking great, two minor things. For the docs, since the ``--dev-nsid=1`` is removed from the examples then a small ``note:: ...`` should be added to the docs describing how to control which namespace to use, as this is useful for user-space drivers. The other thing, ``xnvmec:`` is the label usually used as prefix in the commit messages, so it would great to re-word the first commit and use a "()" on the function name, and be slightly more specific. ``cli: clean up xnvmec_cli_to_opts`` --> ``xnvmec: fix xnvmec_cli_to_opts() by only overwriting given arguments``. Or some better wording...

2022-09-18 08:50 UTC, safl requested changes
This is looking great, two minor things. For the docs, since the ``--dev-nsid=1`` is removed from the examples then a small ``note:: ...`` should be added to the docs describing how to control which namespace to use, as this is useful for user-space drivers. The other thing, ``xnvmec:`` is the label usually used as prefix in the commit messages, so it would great to re-word the first commit and use a "()" on the function name, and be slightly more specific. ``cli: clean up xnvmec_cli_to_opts`` --> ``xnvmec: fix xnvmec_cli_to_opts() by only overwriting given arguments``. Or some better wording...

2022-09-20 08:23 UTC, safl approved these changes

2022-09-20 09:13 UTC, merged