Windows common fixes and document offering
OpenMPDK/xNVMe pull request #300
Opened 2023-07-11 12:59 UTC by rs-sam

Windows backend and its interface offering document.
General complier specific warning issue fix.

2023-07-12 08:06 UTC, safl requested changes
Just one minor thing. Otherwise, great!

Forgot this, please add ``#include <inttypes.h>`` and use the PRIu64 / PRIx64 etc. Macros for print-format-specifiers, since changing them to e.g. ``%llu`` will yield errors for clang / gcc.

2023-07-12 08:06 UTC, safl commented on .reuse/dep5
> -Files: third-party/windows/getopt/*/*
Great.

2023-07-12 08:06 UTC, safl commented on lib/xnvme_be_windows_async_ioring.c
> +#ifdef XNVME_BE_WINDOWS_ASYNC_ENABLED
LGTM.

2023-07-12 08:06 UTC, safl commented on docs/getting_started/toolchain.rst
> +.. literalinclude:: build_windows.rst
Excellent!

2023-07-13 11:22 UTC, karlowich requested changes
Looks good!
I have added a few comments

2023-07-14 07:30 UTC, rs-sam commented on docs/getting_started/index.rst
> +Which you yield output equivalent to:
taken

2023-07-14 07:31 UTC, rs-sam commented on docs/getting_started/index.rst
> +can be used for raw devices via **\\.\PhysiaclDrive<disk number>** device path.
fixed

2023-07-14 07:31 UTC, rs-sam commented on docs/getting_started/index.rst
> +higher queue-depths when compared to sending the command over via the NVMe
fixed

2023-07-14 07:31 UTC, rs-sam commented on docs/getting_started/build_windows.rst
> +  build.bat uninstall
fixed

2023-07-14 07:31 UTC, rs-sam commented on docs/getting_started/index.rst
> +Similar to ``iocp`` interface, only difference is seperate poller is used
fixed

2023-07-14 11:43 UTC, karlowich approved these changes
Great!

2023-07-17 10:25 UTC, safl approved these changes

2023-07-17 10:26 UTC, merged