catch exc iff pkg-config is not in path
OpenMPDK/xNVMe pull request #306
Opened 2023-07-24 13:04 UTC by jwdevantier

`subprocess.run` raises FileNotFoundError iff. binary (pkg-config) is not in PATH.
Catch this error, same as if pkg-config returned a non-zero exit code.

2023-07-24 13:15 UTC, safl requested changes
Look great thanks! Could I bother you with prefixing with: ``fix(py/bindings): ...``?

2023-07-25 08:13 UTC, jwdevantier commented
updated commit statement, sadly CI timed out.

2023-07-25 11:03 UTC, karlowich commented
@jwdevantier  @safl This CI issue occurs on #303 to and is not related to this branch

2023-07-26 15:17 UTC, safl commented
> @jwdevantier @safl This CI issue occurs on #303 too and is not related to this branch

This should now be fixed on https://github.com/OpenMPDK/xNVMe/pull/298 
Trying out this new "merge-queue" feature...

2023-07-28 12:04 UTC, safl approved these changes

2023-07-28 13:56 UTC, merged