feat(cijoe/debian): test KV over fabrics
OpenMPDK/xNVMe pull request #345
Opened 2023-09-13 07:56 UTC by karlowich

This is an experiment

2023-09-19 18:20 UTC, safl requested changes
This is excellent, however, looks like the existing SPDK patches do not apply cleanly.
They need to be rebased for v23.01

2023-09-21 14:37 UTC, sbates130272 commented on cijoe/configs/debian-bullseye.toml
> +
Seems like too many newlines here?

2023-09-22 06:46 UTC, karlowich commented on cijoe/configs/debian-bullseye.toml
> +
Thanks! Fixed.

2023-09-26 09:26 UTC, safl commented
@karlowich since the bump of SPDK is also needed by https://github.com/OpenMPDK/xNVMe/pull/350
How about you extract that into it's own PR? Then we can move that onto ``next`` for this PR as well as the other to consume?

2023-09-26 09:52 UTC, karlowich commented
@safl I agree that is a good idea. However, I think a new version of SPDK is just around the corner, and I think moving to that version is preferred.

2023-09-29 11:30 UTC, safl commented
> @safl I agree that is a good idea. However, I think a new version of SPDK is just around the corner, and I think moving to that version is preferred.

23.09 is out now, how about a PR taking that bump all the way? :)

2023-11-20 11:20 UTC, safl approved these changes
LGTM, thanks!

2023-11-20 11:41 UTC, merged