Pseudo commands support
OpenMPDK/xNVMe pull request #353
Opened 2023-09-28 09:53 UTC by vikash-k5

Pseudo commands (ctrl reset, ns rescan and subsystem reset) support in xNVMe.

1. Adding ctrl reset, ns rescan and subsystem reset.
2. Add pseudo commands testing tool.

2023-10-03 11:38 UTC, safl requested changes
This is great, thank you @vikash-k5 as discussed offline, then I had some change-requests, I have applied them now. They include:

- [x] Correct formating (make format-all)
- [x] Remove NVME_IOCTL_* from public header
    - These should be provided by the on-system UAPI (``linux/nvme_ioctl.h``)
- [x] Dropped changes to ``lib/xnvme_topology.c``
    - These changed the error-handling. Although we currently do no make use of completion status-codes, then for other back-ends this might be useful. Thus, keeping that code in place as it does not prevent / interfere with Linux provided implementation.
- [x] Move cli-logic from test into "tools/xnvme.c"
    - The code added to the ``tests/pseudo_commands.c`` were exactly what the command-line tool needs, thus moved it to the cli instead. This can then be tested via the cijoe testcase.
- [x] Expand CIJOE tests with verification of the new 'xnvme' cli-tool sub-commands
    - ``cijoe/tests/tools/test_xnvme.py``
    - Expand with invocation of the new sub-commands
    
There is one item left, which will ensure that this runs as part for the CI-testing. Can you look into that one?

2023-11-01 09:09 UTC, karlowich commented on tools/xnvme.c
> +		"ctrl-reset",
I think we should rename this and the other occurrences to "ctrlr-reset"

2023-11-01 09:32 UTC, karlowich requested changes
This is looking pretty good. However it is weird that it fails like this:
```
# ERR: 'xnvme_controller_reset()': {errno: -1, msg: 'Operation not permitted'}
# ERR: 'ctrl-reset': {errno: -1, msg: 'Operation not permitted'}
```

I have left some comments.

2023-11-01 09:32 UTC, karlowich commented on tools/xnvme.c
> +			{XNVME_CLI_OPT_URI, XNVME_CLI_POSA},
For each of these, we should add `XNVME_CLI_ADMIN_OPTS` to be able to specify `be` etc.

2023-11-01 09:32 UTC, karlowich commented on cijoe/tests/tools/test_xnvme.py
> +        assert err, "Backend does not support this, yet, does not emit an error"
These assert statements make no sense, we are currently not passing any options along with the command

2023-11-01 09:32 UTC, karlowich commented on lib/xnvme_be_linux_nvme.c
> +	ctx->cpl.status.sct = 0;
Do we need to set these explicitly? Perhaps we should use `ioctl_wrap()` instead of `ioctl()`?

2023-11-01 09:32 UTC, karlowich commented on cijoe/tests/tools/test_xnvme.py
> +def test_subsystem_reset(cijoe, device, be_opts, cli_args):
This test has the same name as the one above, as such we never actually test `subsystem-reset`

2023-11-02 09:22 UTC, karlowich commented
It seems that part of the problem here lies in the fact that these commands are not supposed to be sent to namespaces e.g. `nvme0n1` but rather to the controller e.g. `nvme0`.
I am basing this on the behaviour of nvme-cli where:
`nvme reset /dev/nvme0n1` gives `Error: requesting reset on non-controller handle` 
`nvme reset /dev/nvme0` succeeds

2023-11-02 13:33 UTC, karlowich commented
For the subsystem reset, it would be very useful if we had support for something like the nvme-cli `nvme show-regs` or spdk `spdk_nvme_ctrlr_get_regs_*`

Then we could do something like this:
```
cap = spdk_nvme_ctrlr_get_regs_cap(ctrlr);
if (cap.bits.nssrs == 0) {
	return -ENOTSUP;
}
```
(from spdk [source code](https://github.com/spdk/spdk/blob/986fb7b3ef33fe066da9bc9cb91d86f8db4da0b1/lib/nvme/nvme_ctrlr.c#L1860))

2023-11-13 11:34 UTC, karlowich commented
Hi @vikash-k5,

I have addressed my own comments and pushed the changes required

2023-11-13 11:40 UTC, safl commented
> For the subsystem reset, it would be very useful if we had support for something like the nvme-cli `nvme show-regs` or spdk `spdk_nvme_ctrlr_get_regs_cap`
> 
> Then we could do something like this - getting the Controller Capabilities (figure 36 in base spec) and checking for support:
> 
> ```
> cap = spdk_nvme_ctrlr_get_regs_cap(ctrlr);
> if (cap.bits.nssrs == 0) {
> 	return -ENOTSUP;
> }
> ```
> 
> (from spdk [source code](https://github.com/spdk/spdk/blob/986fb7b3ef33fe066da9bc9cb91d86f8db4da0b1/lib/nvme/nvme_ctrlr.c#L1860))

That is what we have here: https://github.com/OpenMPDK/xNVMe/pull/350

We just needed this PR. to get in first, since it uses the restructured pseudo-command-infra, such that #350 could utilize it. So, once #353 is in, then we can rebase and refactor #350 to make use of pseudo-commands.

2023-11-13 12:28 UTC, safl approved these changes

2023-11-13 12:28 UTC, karlowich submitted a review, later dismissed

2023-11-14 20:35 UTC, safl submitted a review, later dismissed
Thanks @vikash-k5 and @karlowich !

I took the liberty of forcing a change on the PR, that is, use ``ioctl()`` rather than ``ioctl_wrap()``. This is because ``ioctl_wrap()`` is intended for command-passthru and the behavior of that specific ioctl, thus, it does not behave properly not the other ioctls.

In addition, then this PR https://github.com/OpenMPDK/xNVMe/pull/385 was added in preparation.

2023-11-15 11:07 UTC, merged