Makeover
OpenMPDK/xNVMe pull request #418
Opened 2024-01-23 22:14 UTC by safl

2024-01-25 12:17 UTC, karlowich requested changes
Overall looking good - a few comments

2024-01-25 12:17 UTC, karlowich commented on cijoe/workflows/provision-using-tgz.yaml
> +#    xnvme_source: '{{ config.xnvme.repository.sync.remote_path }}'
If this is not needed, I think we should remove it

2024-01-25 12:26 UTC, safl commented on .github/workflows/verify.yml
> +#    - name: Install rust-fmt
Fixed, thanks!

2024-01-25 12:28 UTC, safl commented on .github/workflows/verify.yml
> +        gmake
Fixed, thanks!

2024-01-25 12:29 UTC, safl commented on Makefile
> +		guest_check
I like that it is the same and just using a subset of the steps, then there are fewer workflows to "test".

2024-01-25 12:31 UTC, safl commented on cijoe/configs/debian-bullseye.toml
> +#prefix = "/opt/fio"
Hmm, how about adding a comment instead, informing the user how they can add a prefix instead?

2024-01-25 12:32 UTC, safl commented on cijoe/scripts/git_sync.py
> +Here is what is does:
fixed, thanks.

2024-01-25 12:57 UTC, safl commented on cijoe/configs/debian-bullseye.toml
> +#prefix = "/opt/fio"
Went this way...

2024-01-26 12:51 UTC, mbrsamsung approved these changes
Looks very nice. Good job!

2024-01-26 12:55 UTC, merged