feat(meson): added unit tests
OpenMPDK/xNVMe pull request #455
Opened 2024-04-09 11:50 UTC by NaddiNadja

The unit tests can be run by compiling with the meson option 'tests' set to true and then running `meson test` in the build directory.

2024-04-09 13:22 UTC, karlowich requested changes
This is great!
In addition to the comment I left, I think we should add a `make test`.
You can take inspiration from `make install` in the `Makefile`

2024-04-09 13:22 UTC, karlowich commented on tests/meson.build
> +  'delay_identification.c': [],
We don't need to skip this.
It works with the arguments: `['open',  '1GB']`

2024-04-09 13:26 UTC, karlowich commented
Additionally, it would be great to have the same functionality for the executables in `xnvme/tools/`

2024-04-18 14:11 UTC, karlowich approved these changes
Looks good!

2024-04-19 09:06 UTC, ankit-sam approved these changes
Looks good, but just wondering if this should include all the tests (say from xnvme.c we are missing a bunch like, set & get features, dsm, log pages etc).

2024-04-19 09:08 UTC, karlowich commented
@ankit-sam We are only running the tests that work with the ramdisk. The idea is when we add more functionality to the ramdisk, we can test more things

2024-04-19 09:11 UTC, merged