fix(ci/qcow2): prepare for building qcow2 images automatically
OpenMPDK/xNVMe pull request #555
Opened 2024-11-21 13:40 UTC by NaddiNadja

This is necessary for the github actions in this repo:
https://github.com/xnvme/xnvme-qcow2/

2024-11-21 14:16 UTC, karlowich requested changes
It seems like you're only changing something for FreeBSD - so why the changes to the `bootimg-debian` workflow?

2024-11-21 14:16 UTC, karlowich commented on cijoe/configs/freebsd-14.toml
> +init_using_bootimage.url = "https://refenv.fra1.digitaloceanspaces.com/boot_images/freebsd-13.1-ksrc-amd64.qcow2"
This should remain `freebsd-14.1` right?

2024-11-26 08:21 UTC, NaddiNadja commented
> It seems like you're only changing something for FreeBSD - so why the changes to the `bootimg-debian` workflow?

This is necessary for the github actions in this repo:
https://github.com/xnvme/xnvme-qcow2/

2024-11-26 14:43 UTC, safl reviewed
It would be great if you added the description from the comments in the commit message: 

```
It's about adding the xnvme provisioning of qemu images from tgz to the workflows. This is necessary for the github actions in this repo.
```
Re-formulated... that is...

2024-12-03 09:19 UTC, NaddiNadja commented
> It would be great if you added the description from the comments in the commit message:

done :)

2024-12-05 12:22 UTC, safl approved these changes
LGTM

2024-12-10 09:25 UTC, karlowich approved these changes
lgtm.

(Is it intentional that the freebsd workflow include at least twice the amount of documentation?)

2024-12-10 10:09 UTC, NaddiNadja commented
> (Is it intentional that the freebsd workflow include at least twice the amount of documentation?)

@karlowich, it's a copy-paste of the FreeBSD 13 workflow, so I didn't notice the different length of the docstrings. Should I write more in the Debian workflow docstring?

2024-12-10 10:18 UTC, karlowich commented
@NaddiNadja I don't think it is super important - but then again, why not.

2024-12-18 10:23 UTC, merged