feat(cijoe/tests): add fdp and zns to fio tests
OpenMPDK/xNVMe pull request #564
Opened 2024-12-19 13:26 UTC by karlowich

This follows the examples from the fio GH repo: [fdp](https://github.com/axboe/fio/blob/master/examples/xnvme-fdp.fio) and [zns](https://github.com/axboe/fio/blob/master/examples/xnvme-zoned.fio)

2025-01-16 08:23 UTC, NaddiNadja requested changes
Just a small thing :)

2025-01-16 08:23 UTC, NaddiNadja commented on cijoe/tests/apps/test_fio.py
> +    hugepage_path = cijoe.config.options.get("hugetlbfs", {}).get("mount_point", "")
You can use `cijoe.getconf("hugetlbfs.mount_point", "")` (added in v0.9.38 of cijoe iirc)

2025-01-16 08:23 UTC, NaddiNadja commented on cijoe/tests/apps/test_fio.py
> +    hugepage_path = cijoe.config.options.get("hugetlbfs", {}).get("mount_point", "")
Again, use `cijoe.getconf("hugetlbfs.mount_point", "")`

2025-01-16 10:26 UTC, karlowich commented on cijoe/tests/apps/test_fio.py
> +    hugepage_path = cijoe.config.options.get("hugetlbfs", {}).get("mount_point", "")
Done

2025-01-16 10:26 UTC, karlowich commented on cijoe/tests/apps/test_fio.py
> +    hugepage_path = cijoe.config.options.get("hugetlbfs", {}).get("mount_point", "")
Done

2025-01-16 11:59 UTC, NaddiNadja approved these changes
nice lgtm :)

2025-01-17 09:22 UTC, safl approved these changes
lgtm.

2025-01-17 12:10 UTC, merged