fix(be/spdk): don't detach in-use enumerated controllers
OpenMPDK/xNVMe pull request #566
Opened 2024-12-21 06:09 UTC by jadoc

If `XNVME_ENUMERATE_DEV_KEEP_OPEN` is returned from the callback during enumeration, the SPDK controller underlying the open device must not be detached. Only deref the controller if the device is closed. Conditionally detach controllers only if their reference count is zero.

It is now valid for a controller to have a reference count of zero and not be cleaned up yet. Entries in the reference count array may not be reused if the controller pointer is non-null. A controller with a zero reference count may be still be incremented later. A new cleanup routine allows deferred detachment of all controllers with a zero refcount.

This change is an attempt to fix #565.

2024-12-27 12:29 UTC, karlowich commented
Hi @jadoc, thank you very much for your contribution!
Overall it looks very good, however there seems to be a bug when enumerating devices with multiple namespaces causing the same ctrlr to be detached more than once.
```bash
...
  - {uri: '0000:03:00.0', dtype: 0x2, nsid: 0x1, csi: 0x0, subnqn: 'nqn.2019-08.org.qemu:deadbeef'}
# DBG:xnvme_be.c:xnvme_be_factory-276: INFO: checking be: 'spdk'
# DBG:xnvme_be.c:xnvme_be_factory-307: INFO: obtained backend instance be: 'spdk'
# DBG:xnvme_be_spdk_dev.c:_spdk_env_init-245: INFO: already initialized
# DBG:xnvme_be_spdk_dev.c:_spdk_env_init-270: INFO: spdk_env_is_initialized: 1
# DBG:xnvme_be_spdk_dev.c:xnvme_be_spdk_state_init-807: INFO: found dev->ident.uri: '0000:03:00.0' via cref_lookup()
# DBG:xnvme_be_spdk_dev.c:xnvme_be_spdk_state_init-851: INFO: re-using previously attached controller
# DBG:xnvme_be_spdk_dev.c:xnvme_be_spdk_state_init-901: INFO: open() : OK
# DBG:xnvme_be.c:xnvme_be_factory-312: INFO: obtained device handle
# DBG:xnvme_dev.c:_dev_idfy_csi-171: INFO: looks like csi(ZNS)
  - {uri: '0000:03:00.0', dtype: 0x2, nsid: 0x2, csi: 0x2, subnqn: 'nqn.2019-08.org.qemu:deadbeef'}
# DBG:xnvme_be_spdk_dev.c:_cref_deref-107: INFO: refcount: 0 => detaching
# DBG:xnvme_be_spdk_dev.c:_cref_cleanup-136: INFO: refcount: 0 => detaching
xnvme: nvme.c:61: nvme_ctrlr_detach_async: Assertion `ref_count > 0' failed.
Aborted
```
As seen in the debug output above `spdk_nvme_detach()` is called both from `_cref_deref()` and `_cref_cleanup()`.

2024-12-28 09:44 UTC, jadoc commented
I don't think there's an error in the new logic per se, but I inadvertently unmasked an existing bug. The current enumeration logic calls `_cref_insert()` once per namespace on the same controller, which I don't believe is safe. This has been leaving junk in `g_cref`. Only now that I'm walking `g_cref` with `_cref_cleanup()` is the corruption becoming apparent.

I think the answer is to replace both `_cref_insert()` and `_cref_lookup()` with a common `_cref_ref()` that safely does the right thing depending on whether the controller currently exists in the table.

2024-12-28 11:26 UTC, karlowich commented
@jadoc Yes, it appears you are right - the logic was broken before your changes.
I agree that what we need is some logic to either increment the refcount if the ctrlr exists OR insert it, instead of potentially inserting the same controller multiple times.
As for merging the two functions, I cannot decide if it is nicer or not.

2024-12-28 11:31 UTC, karlowich commented
Changing `_cref_insert()` to the below fixes the assertion error:
```C
static int
_cref_insert(struct xnvme_ident *ident, struct spdk_nvme_ctrlr *ctrlr)
{
        if (!ctrlr) {
                XNVME_DEBUG("FAILED: !ctrlr");
                return -EINVAL;
        }

        for (int i = 0; i < XNVME_BE_SPDK_CREFS_LEN; ++i) {
                if (g_cref[i].ctrlr) {
                        if (g_cref[i].ctrlr != ctrlr) {
                                continue;
                        }
                        g_cref[i].refcount += 1;
                        return 0;
                }

                g_cref[i].ctrlr = ctrlr;
                g_cref[i].refcount += 1;
                strncpy(g_cref[i].uri, ident->uri, XNVME_IDENT_URI_LEN);

                return 0;
        }

        return -ENOMEM;
}
```

2024-12-28 22:58 UTC, jadoc commented
@karlowich
> Changing `_cref_insert()` to the below fixes the assertion error

Your proposed fix doesn't work in the case where a previous entry in the list has been freed. We must compare every entry in the list before concluding that the controller isn't already in the table. This is the best we can do unless this were replaced with a hash table. [^resizeable]

I have proposed an implementation of `_cref_ref()` that safely combines both the insert and lookup use cases. Let me know what you think.

There should probably be an explicit tests for the following. I'm not familiar with the test framework used by the project, so I'll have to figure out how much effort that will be.
1) Keeping devices open after enumeration.
2) Closing old devices before opening new ones.


[^resizeable]: Actually, using a resizable hash table like [uthash](/troydhanson/uthash) is probably a good idea regardless.

2024-12-29 15:25 UTC, karlowich requested changes
This is great!
One minor nitpick.

2024-12-29 15:25 UTC, karlowich commented on lib/xnvme_be_spdk_dev.c
> +			if (free_pos < 0 && !g_cref[i].ctrlr) {
```suggestion
			if (free_pos < 0) {
```
`!g_cref[i].ctrlr` will always be true if we hit this path

2024-12-29 15:34 UTC, karlowich commented
@jadoc Thanks again for your contribution!

> I'm not familiar with the test framework used by the project

Our tests are primarily C programs residing in `xnvme/tests`, I think the functionality we need to test fits in `xnvme/tests/enum`.
The tests are orchestrated from python in `xnvme/cijoe/tests`, i.e. `xnvme/cijoe/tests/logic/test_xnvme_tests_enum.py`

2024-12-30 07:18 UTC, jadoc commented
@karlowich 
> Our tests are primarily C programs residing in `xnvme/tests`, I think the functionality we need to test fits in `xnvme/tests/enum`. The tests are orchestrated from python in `xnvme/cijoe/tests`, i.e. `xnvme/cijoe/tests/logic/test_xnvme_tests_enum.py`

The problem I was having was with CIJOE running QEMU. My QEMU installation doesn't support NVMe key-value command set. I don't know if this is a matter of building the latest version of QEMU from source or if a special patch set is necessary to make it work. Alternatively, maybe I can disable the KV devices and just run the specific tests in question, but those enumeration tests may expect the KV devices to be there.

2024-12-30 20:41 UTC, karlowich submitted a review, later dismissed

2024-12-30 20:43 UTC, karlowich commented
@jadoc We're using the `for-xnvme` branch from this [fork](https://github.com/SamsungDS/qemu).

2025-01-08 07:39 UTC, jadoc commented
I tried adding tests, but it looks like keeping devices open is broken for linux and vfio backends as well. I guess I'll have to mark those as skip for now.

2025-01-08 11:42 UTC, karlowich commented
@jadoc This is great!
It looks like the part failing on linux is not related to keeping the devices open, the error is: 
`errno: -25, msg: 'Inappropriate ioctl for device'`.
This looks like maybe the flush is the problem, depending on which I/O interface is chosen this might not be supported.
I suggest sending an identify command instead of the flush.

For the vfio backend enumeration is not supported, so we expect it to fail.

2025-01-09 09:54 UTC, safl reviewed
Thanks for this, @jadoc! This is an excellent contribution.

I’ve added an inline suggestion with additional details to @karlowich’s proposal on using an identify command. Other than that, please proceed with signing off the commits.

Again, thank you!

2025-01-09 09:54 UTC, safl commented on tests/enum.c
> +#define MAX_DEVS 100
nice.

2025-01-09 09:54 UTC, safl commented on tests/enum.c
> +		ctx.cmd.common.opcode = XNVME_SPEC_NVM_OPC_FLUSH;
The flush command will fail on NVMe devices that don't support the NVM command set (e.g., KV or computation storage devices). As @karlowich suggested, consider using an admin command instead. This ensures the check is independent of the device's command set support during testing.

One downside is that you need to allocate a buffer for the payload. However, you can mitigate this by allocating the buffer before the loop, reusing it throughout, and deallocating it afterward.

For the command itself, you can use a helper like ``xnvme_adm_idfy_ctrlr()``, which constructs a mandatory identify controller command.

2025-01-10 08:02 UTC, jadoc commented on tests/enum.c
> +		ctx.cmd.common.opcode = XNVME_SPEC_NVM_OPC_FLUSH;
> The flush command will fail on NVMe devices that don't support the NVM command set (e.g., KV or computation storage devices).

That's interesting because in my reading of the NVMe base specification version 2.1, section 7 states that flush is valid for all command sets, and section 3.1.3.4 states that support for flush is mandatory for all I/O controllers. Also, if it were a matter of underlying device support, I would expect the command to fail with the SPDK backend, but flush apparently succeeds for all devices with SPDK.

The difference in behavior between the Linux backend and the SPDK backend is that enumeration on SPDK only returns devices of type `XNVME_DEV_TYPE_NVME_NAMESPACE` while Linux returns a mixture of  `XNVME_DEV_TYPE_NVME_CONTROLLER` and `XNVME_DEV_TYPE_NVME_NAMESPACE`. If I locally tweak the test to skip over the `XNVME_DEV_TYPE_NVME_CONTROLLER` devices, it passes. It appears that `XNVME_DEV_TYPE_NVME_CONTROLLER` corresponds to "Administrative controller" as defined in section 1.5.5 of the base spec.

Anyway, I'll switch to using an admin identify controller command.

2025-01-10 08:39 UTC, jadoc commented on tests/enum.c
> +		ctx.cmd.common.opcode = XNVME_SPEC_NVM_OPC_FLUSH;
I decided not to allocate the buffer outside the loop, as `xnvme_buf_alloc()` allows for device-specific behavior.

If the tests pass, I'll rebase into a single commit.

2025-01-10 09:58 UTC, safl commented on tests/enum.c
> +		ctx.cmd.common.opcode = XNVME_SPEC_NVM_OPC_FLUSH;
> > The flush command will fail on NVMe devices that don't support the NVM command set (e.g., KV or computation storage devices).
> 
> That's interesting because in my reading of the NVMe base specification version 2.1, section 7 states that flush is valid for all command sets, and section 3.1.3.4 states that support for flush is mandatory for all I/O controllers. Also, if it were a matter of underlying device support, I would expect the command to fail with the SPDK backend, but flush apparently succeeds for all devices with SPDK.
> 

You are absolutely right, my memory betrayed me.

2025-01-10 10:19 UTC, karlowich commented
@jadoc The only thing that fails is the vfio backend.
I think adding a skip is appropriate.
```PYTHON
if be_opts["be"] in ["vfio"]:
        pytest.skip(reason=f"[be={be_opts['be']}] enumeration not supported")
```

2025-01-13 00:03 UTC, jadoc commented
@karlowich
> For the vfio backend enumeration is not supported, so we expect it to fail.

Something doesn't add up. I see other enumeration tests pass for vfio. I think there may actually be a bug with keeping vfio devices open. Anyway, I won't attempt to address it here.

2025-01-13 10:31 UTC, karlowich commented
@jadoc It is true that some tests look like they enumerate successfully with vfio, this is a bug in `xnvme_enumerate()`.
I will fix that in a separate PR.

2025-01-13 12:20 UTC, karlowich submitted a review, later dismissed
Great!

2025-01-14 05:20 UTC, jadoc commented
@karlowich
> @jadoc It is true that some tests look like they enumerate successfully with vfio, this is a bug in `xnvme_enumerate()`. I will fix that in a separate PR.

Ah, I think the problem is in the tests. They don't actually verify that a non-zero number of devices were enumerated, which seems pretty important. I'm unable to debug the vfio stuff myself properly because my test rig doesn't have an IOMMU and I'm having trouble getting QEMU to emulate one, at least when combined with my CPU.

2025-01-14 11:13 UTC, karlowich commented
@jadoc I have fixed the bug here: #571 
Also, we prefer if you rebase on next instead of the merge commit.

2025-01-15 07:31 UTC, jadoc commented
@karlowich 
> we prefer if you rebase on next instead of the merge commit.

Done.

2025-01-15 10:17 UTC, karlowich approved these changes

2025-01-15 10:30 UTC, safl approved these changes
Thanks @jadoc !

2025-01-15 10:31 UTC, merged