be:macos: Add simple backend for macOS
OpenMPDK/xNVMe pull request #68
Opened 2022-04-04 13:28 UTC by Baekalfen

New backend which supports macOS mostly using existing POSIX functionality. Although with the addition to  use the NVMeSMARTLibExternal.h provided by Xcode to query some information from the target disk. This does not enable arbitrary NVMe commands to be sent to a disk, but rather support for Get Log Page and Identify commands.

2022-04-05 08:28 UTC, Baekalfen commented
Blocked by #55

2022-04-05 09:19 UTC, safl commented
Regarding the first commit. The issue you are experiencing is not a general ``aarch64`` issue.
Disabling the SPDK backend on all ``aarch`` is therefore not a good solution.
See here: https://github.com/OpenMPDK/xNVMe/pull/66
So, either:
1) Find the root cause of the issue and make a patch for SPDK, we can carry this patch:
  - ``subprojects/packagefiles/spdk/patches/`` until we get the patch upstreamed in SPDK
2) Alter the commit to do a work-around specific to where you are seeing the issue.

2022-04-05 09:41 UTC, safl commented
Regarding the second commit ``be:psync,macos: unify pread/pwrite across Unix-like platforms``. Thanks for taking a stab at this, it is an area that would be really great to improve for re-use. However, I am not certain this commit is the way to go. There are some things that need a bit more investigation when it comes the platform-specific behavior and error-handling on even the simplest things like ``pread()``/``pwrite()``.
Also, on MacOS, it looks like some special handling is needed for fsync():
* https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/fsync.2.html#//apple_ref/doc/man/2/fsync
* https://twitter.com/marcan42/status/1494213862970707969

So, instead of the refactor, how about just doing this:
* export the POSIX ``cmd_io()`` implementation and re-use it in ``lib/xnvme_be_macos_sync.c``
* add cmd_iov() in ``lib/xnvme_be_macos_sync.c``

Right now, I would prefer not to alter the behavior of all of POSIX, Linux, and FreeBSD for the sake of the MacOS implementation. I would much rather like that the MacOS backend is added and then we can investigate a proper re-usable ``common``/``base`` implementation. Taking other things into account such as the ``common/base`` backend state and other things that are commonly needed/re-used.

**TLDR**; to unblock the addition of the MacOS addition, then just add the MacOS implementation and re-use the ``cmd_io()`` from the POSIX backend.

2022-04-05 10:05 UTC, Baekalfen commented
> Regarding the first commit `build:meson: exclude SPDK from building on aarch64 systems`. The issue you are experiencing is not a general `aarch64` issue. Disabling the SPDK backend on all `aarch` is therefore not a good solution. See here: #66 So, either:
> 
> 1. Find the root cause of the issue and make a patch for SPDK, we can carry this patch:
> 
> * `subprojects/packagefiles/spdk/patches/` until we get the patch upstreamed in SPDK
> 
> 2. Alter the commit to do a work-around specific to where you are seeing the issue.

I'll drop it from here. It was just part of the branch before you made the comments in #66

2022-04-05 10:07 UTC, Baekalfen commented
> Regarding the second commit `be:psync,macos: unify pread/pwrite across Unix-like platforms`. Thanks for taking a stab at this, it is an area that would be really great to improve for re-use. However, I am not certain this commit is the way to go. There are some things that need a bit more investigation when it comes the platform-specific behavior and error-handling on even the simplest things like `pread()`/`pwrite()`. Also, on MacOS, it looks like some special handling is needed for fsync():
> 
> * https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/fsync.2.html#//apple_ref/doc/man/2/fsync
> * https://twitter.com/marcan42/status/1494213862970707969
> 
> So, instead of the refactor, how about just doing this:
> 
> * export the POSIX `cmd_io()` implementation and re-use it in `lib/xnvme_be_macos_sync.c`
> * add cmd_iov() in `lib/xnvme_be_macos_sync.c`
> 
> Right now, I would prefer not to alter the behavior of all of POSIX, Linux, and FreeBSD for the sake of the MacOS implementation. I would much rather like that the MacOS backend is added and then we can investigate a proper re-usable `common`/`base` implementation. Taking other things into account such as the `common/base` backend state and other things that are commonly needed/re-used.
> 
> **TLDR**; to unblock the addition of the MacOS addition, then just add the MacOS implementation and re-use the `cmd_io()` from the POSIX backend.

Maybe I should have pointed it out more clearly. That commit is actually from #55

2022-05-17 14:06 UTC, Baekalfen commented
@safl If you have no more comments, then I consider this PR ready for merge.

2022-05-24 14:25 UTC, safl requested changes
See in-line comments, adding to those:
* Could the introduction of ``additional_link_args`` / ``link_args`` in meson be handled in a manner similar to ``dependency('threads')``?

2022-05-24 14:25 UTC, safl commented on toolbox/cijoe-pkg-xnvme/testplans/xnvme-base-macos.plan
> +  XNVME_URI: "/dev/disk4"
The ``XNVME_URI`` be removed from here and instead adjust the construction of ``XNVME_URI`` in ``toolsbox/cijoe-pkg-xnvme/envs/refenv-xnvme.sh`` and ``toolsbox/cijoe-pkg-xnvme/envs/refenv-xnvme.sh`.

2022-05-24 14:25 UTC, safl commented on toolbox/cijoe-pkg-xnvme/testcases/examples-xnvme_hello.sh
> -#!/bin/bash
The commit title should be something along the lines of: ``toolbox:cijoe: change shebang to '/usr/bin/env bash'``

And the body should describe why this is needed.

2022-05-25 15:24 UTC, safl approved these changes

2022-05-25 15:48 UTC, safl commented
Thanks!

2022-05-25 15:48 UTC, merged